# Generated by Django 5.2.7 on 2025-11-04 13:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("intro", 7),
                    ("services_showcase", 11),
                    ("highlights", 14),
                    ("testimonials_showcase", 17),
                    ("cta_section", 19),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("background_image", 2),
                                ("primary_button_text", 3),
                                ("primary_button_url", 4),
                                ("secondary_button_text", 3),
                                ("secondary_button_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 3),
                                ("content", 6),
                                ("image", 2),
                                ("button_text", 3),
                                ("button_url", 4),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 3),
                                ("title", 0),
                                ("description", 8),
                                ("link_text", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("intro", 1), ("services", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 0), ("label", 0)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("highlights", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("company", 3), ("feedback", 8), ("photo", 2)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("subtitle", 3), ("testimonials", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("button_text", 0),
                                ("button_url", 18),
                                ("background_image", 2),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tagline",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
